name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
          workspaces: 'src-tauri'
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install NPM Dependencies
        run: pnpm i
      - name: Update Meta
        run: |
          $tag = git describe --tags --abbrev=0 2>$null
          if (-not $tag) { $tag = "0.0.0" }
          $TAG = $tag -replace '^v', ''
          $PKGVER = "r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          $cstTimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("China Standard Time")
          $utcNow = [System.DateTime]::UtcNow
          $cstTime = [System.TimeZoneInfo]::ConvertTimeFromUtc($utcNow, $cstTimeZone)
          $BUILDMETA = $cstTime.ToString("yyMMddHHmm")
          (Get-Content ./src-tauri/Cargo.toml -Raw) -replace '(?m)^(version = "\d+\.\d+\.\d+)', "version = `"$TAG-$PKGVER+$BUILDMETA" | Set-Content ./src-tauri/Cargo.toml -Encoding utf8
      - name: Build
        run: pnpm build
      - name: Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: src-tauri/target/release/*.exe
